name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Cache Deno dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock', '**/deno.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Run check
        run: deno task check

      - name: Run build
        run: deno task build && deno task clean:no-html

      - name: Add CNAME for custom domain
        run: echo "todo-template.lalala-233.top" > dist/CNAME

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy:
    needs: check-and-build
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
